### ISSUE TITLE
[Suggestion] Run the script each x times

### ISSUE THREAD

**Issue by Mara-Li** [ozntel/oz-clear-unused-images-obsidian#1]
Hello! Great plug-in! It helps me to clean around 100 images (yup... Copy paste 🙈)

I was wondering if it's possible to add an option to :
- Run each x time, like each 2 days, each 2 hours...
- Run when obsidian is open, like an autoclean.

Thank you anyway! ✨

**Comment by ozntel** [comment]
Hi @Mara-Li

I am happy that the plugin helps you to keep your vault clean. It means I succeeded in what I aimed :)

As per your request, I worked a little bit on a function, which runs each X minutes, or during the initial load of Obsidian. You can find this experimental feature under the branch:

https://github.com/ozntel/oz-clear-unused-images-obsidian/tree/auto-clear-feature

If you want to try the feature and give me your feedback, I would be grateful (You can simply download the branch files and use the main.js file together with manifest.json - but not from the release)

Please kindly make sure that **you have a backup of your vault** before you try the plugin out since I wouldn't like to cause you to lose your images. 

Settings look like below:

<img width="1488" alt="auto-clear feature" src="https://user-images.githubusercontent.com/55187568/117811746-396dc880-b261-11eb-99eb-a945697cab1a.png">

Thanks!

**Comment by Mara-Li** [comment]
Unfortunately, it doesn't seems to work and my files are deleted. My folder with these images references are in the vault/Ecriture.

**Comment by ozntel** [comment]
I didn't understand exactly what is happening. Would you be able to specify the problem? It shouldn't delete any images unless they are reference in any of Markdown notes.
The branch I provided above doesn't have implemented the new version features like excluding folder,  deleted image destination choice, etc.

**Comment by Mara-Li** [comment]
In fact I fail of subject. I don't use this branch yet, and i was talking about the folder exclusion ! I'm sorry for this fail !

**Comment by ozntel** [comment]
> Unfortunately, it doesn't seems to work and my files are deleted. My folder with these images references are in the vault/Ecriture.

You need to provide the folder name as `Ecriture` if the images are directly under this folder. 
The plugin will match only the final folder name.

**Comment by Mara-Li** [comment]
So i will be better if we can exclude subfolder as well (or lock to one folder)

**Comment by ozntel** [comment]
> So i will be better if we can exclude subfolder as well (or lock to one folder)

As I mentioned, you can exclude any folder or subfolder. 

Let's say you have your `vault/Ecriture` folder but you want to exclude images that are only under `vault/Ecriture/Personal/Smart`. To be able to exclude these images, you need to provide the name of the subfolder `Smart` in the plugin settings and it will exclude all images under `Smart` from the deletion. 

But you need to take into consideration that all folders with the name `Smart` will be excluded no matter where the folder is located. So it would be better to give a unique name to the folders you want to exclude. The level of the subfolder doesn't matter. The plugin checks only the name of the folder, to which the image directly belongs.

Hope this clarifies.

**Comment by ozntel** [comment]
`Run the script each x times` function is also included in the roadmap of the plugin.
