### ISSUE TITLE
Where do deleted images go?

### ISSUE THREAD

**Issue by luckman212** [ozntel/oz-clear-unused-images-obsidian#2]
iyi bayramlar...great work on this plugin @ozntel !

I am wondering, where do the deleted images go - do they get immediately destroyed, or end up in Vault trash etc?

**Comment by ozntel** [comment]
hi @luckman212, iyi bayramlar! 

I am happy to hear that plugin is helpful.

Within the current setup, the images are permanently deleted. 

However, I can implement a feature in the future to give a choice to the users so that they can select if they want to delete permanently or move to the trash by either:

  1. Including additional command for the .trash option
  2. Creating custom settings for the plugin

**Comment by luckman212** [comment]
Very good idea. I think to be able to choose either 1) delete immediately or 2) move to .trash in the settings window would be a very nice feature for sure.

**Comment by ozntel** [comment]
Hi @luckman212 I just released a version, which gives you a choice so that you can select where to move files once they are deleted. Basically you can now :

1. move to `.trash` of Obsidian
2. move to Operating System Trash 
3. delete permanently

Hope this will help.

**Comment by luckman212** [comment]
It works beautifully 🚀  Thank you very much for this.
